// packages/react/src/alignment-left.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
import { shallowEqual } from './_utils'
const AlignmentLeftIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { ariaHidden:"true",height:"1em",strokeLinejoin:"round",viewBox:"0 0 16 16",width:"1em",dangerouslySetInnerHTML:{__html:'<path fill-rule="evenodd" clip-rule="evenodd" d="M1.75 2H1V3.5H1.75H14.25H15V2H14.25H1.75ZM1 7H1.75H9.25H10V8.5H9.25H1.75H1V7ZM1 12H1.75H11.25H12V13.5H11.25H1.75H1V12Z" fill="currentColor"></path>'},...p }), shallowEqual)
AlignmentLeftIcon.displayName = 'AlignmentLeftIcon'
export default AlignmentLeftIcon

// src/vue/alignment-left.vue
<template>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.75 2H1V3.5H1.75H14.25H15V2H14.25H1.75ZM1 7H1.75H9.25H10V8.5H9.25H1.75H1V7ZM1 12H1.75H11.25H12V13.5H11.25H1.75H1V12Z" fill="currentColor"></path></svg>
</template>
