// src/react/list-filter.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
import { shallowEqual } from './_utils'
const ListFilterIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { ariaHidden:"true",height:"1em",strokeLinejoin:"round",viewBox:"0 0 16 16",width:"1em",dangerouslySetInnerHTML:{__html:'<path fill-rule="evenodd" clip-rule="evenodd" d="M1 2H1.75H14.25H15V3.5H14.25H1.75H1V2ZM5 12H5.75H10.25H11V13.5H10.25H5.75H5V12ZM3.75 7H3V8.5H3.75H12.25H13V7H12.25H3.75Z" fill="currentColor"></path>'},...p }), shallowEqual)
ListFilterIcon.displayName = 'ListFilterIcon'
export default ListFilterIcon

// packages/vue/src/list-filter.vue
<template functional>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 2H1.75H14.25H15V3.5H14.25H1.75H1V2ZM5 12H5.75H10.25H11V13.5H10.25H5.75H5V12ZM3.75 7H3V8.5H3.75H12.25H13V7H12.25H3.75Z" fill="currentColor"></path></svg>
</template>
