// src/react/pause-circle.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
export const PauseCircleIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { strokeLinejoin:"round",viewBox:"0 0 16 16",width:"1em",height:"1em",dangerouslySetInnerHTML:{__html:'<path fill="currentColor" fill-rule="evenodd" d="M14.5 8a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0Zm-5.5-2.5h-5v5h5v-5Z" clip-rule="evenodd"></path>'},...p }))
PauseCircleIcon.displayName = 'PauseCircleIcon'

// packages/vue/src/pause-circle.vue
<template>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill="currentColor" fill-rule="evenodd" d="M14.5 8a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0Zm-5.5-2.5h-5v5h5v-5Z" clip-rule="evenodd"></path></svg>
</template>
