// src/react/PlayCircle.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
export const PlayCircleIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { height:"16",strokeLinejoin:"round",viewBox:"0 0 16 16",width:"16",dangerouslySetInnerHTML:{__html:'<path fill="#666" fill-rule="evenodd" d="M14.5 8a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM6 11l5.5-3L6 5v6Z" clip-rule="evenodd" style="fill:currentColor;"></path>'},...p }))
PlayCircleIcon.displayName = 'PlayCircleIcon'

// packages/vue/src/play-circle.vue
<template functional>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill="#666" fill-rule="evenodd" d="M14.5 8a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM6 11l5.5-3L6 5v6Z" clip-rule="evenodd" style="fill:currentColor;"></path></svg>
</template>
