// packages/react/src/slash-back.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
import { shallowEqual } from './_utils'
const SlashBackIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { ariaHidden:"true",height:"1em",strokeLinejoin:"round",viewBox:"0 0 16 16",width:"1em",dangerouslySetInnerHTML:{__html:'<path fill-rule="evenodd" clip-rule="evenodd" d="M11.9849 15.3939L11.6894 14.7046L5.68942 0.704556L5.39398 0.0151978L4.01526 0.606077L4.3107 1.29544L10.3107 15.2954L10.6061 15.9848L11.9849 15.3939Z" fill="currentColor"></path>'},...p }), shallowEqual)
SlashBackIcon.displayName = 'SlashBackIcon'
export default SlashBackIcon

// packages/vue/src/slash-back.vue
<template>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.9849 15.3939L11.6894 14.7046L5.68942 0.704556L5.39398 0.0151978L4.01526 0.606077L4.3107 1.29544L10.3107 15.2954L10.6061 15.9848L11.9849 15.3939Z" fill="currentColor"></path></svg>
</template>
