// packages/vue/src/alignment-center.vue
<template>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.75 2H1V3.5H1.75H14.25H15V2H14.25H1.75ZM3.5 7.25H4.25H11.75H12.5V8.75H11.75H4.25H3.5V7.25ZM2.5 12.5H3.25H12.75H13.5V14H12.75H3.25H2.5V12.5Z" fill="currentColor"></path></svg>
</template>

// src/react/alignment-center.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
import { shallowEqual } from './_utils'
export const AlignmentCenterIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { strokeLinejoin:"round",viewBox:"0 0 16 16",width:"1em",height:"1em",dangerouslySetInnerHTML:{__html:'<path fill-rule="evenodd" clip-rule="evenodd" d="M1.75 2H1V3.5H1.75H14.25H15V2H14.25H1.75ZM3.5 7.25H4.25H11.75H12.5V8.75H11.75H4.25H3.5V7.25ZM2.5 12.5H3.25H12.75H13.5V14H12.75H3.25H2.5V12.5Z" fill="currentColor"></path>'},...p }), shallowEqual)
AlignmentCenterIcon.displayName = 'AlignmentCenterIcon'
