// src/vue/chart-bar-random.vue
<template>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill-rule="evenodd" clip-rule="evenodd" d="M14 1V1.75V14.25V15H12.5V14.25V1.75V1H14ZM8.75 6V6.75V14.25V15H7.25V14.25V6.75V6H8.75ZM3.5 4.75V4H2V4.75V14.25V15H3.5V14.25V4.75Z" fill="currentColor"></path></svg>
</template>

// src/react/chart-bar-random.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
export const ChartBarRandomIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { strokeLinejoin:"round",viewBox:"0 0 16 16",width:"1em",height:"1em",dangerouslySetInnerHTML:{__html:'<path fill-rule="evenodd" clip-rule="evenodd" d="M14 1V1.75V14.25V15H12.5V14.25V1.75V1H14ZM8.75 6V6.75V14.25V15H7.25V14.25V6.75V6H8.75ZM3.5 4.75V4H2V4.75V14.25V15H3.5V14.25V4.75Z" fill="currentColor"></path>'},...p }))
ChartBarRandomIcon.displayName = 'ChartBarRandomIcon'
