// packages/vue/src/chart-bar-middle.vue
<template>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill-rule="evenodd" clip-rule="evenodd" d="M8.75 1V1.75V14.25V15H7.25V14.25V1.75V1H8.75ZM3.5 9V9.75V14.25V15H2V14.25V9.75V9H3.5ZM14 6.75V6H12.5V6.75V14.25V15H14V14.25V6.75Z" fill="currentColor"></path></svg>
</template>

// src/react/ChartBarMiddle.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
export const ChartBarMiddleIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { height:"16",strokeLinejoin:"round",viewBox:"0 0 16 16",width:"16",dangerouslySetInnerHTML:{__html:'<path fill-rule="evenodd" clip-rule="evenodd" d="M8.75 1V1.75V14.25V15H7.25V14.25V1.75V1H8.75ZM3.5 9V9.75V14.25V15H2V14.25V9.75V9H3.5ZM14 6.75V6H12.5V6.75V14.25V15H14V14.25V6.75Z" fill="currentColor"></path>'},...p }))
ChartBarMiddleIcon.displayName = 'ChartBarMiddleIcon'
