// src/vue/gps.vue
<template>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path d="M1 6L15 1L10 15L7.65955 8.91482C7.55797 8.65073 7.34927 8.44203 7.08518 8.34045L1 6Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="bevel" fill="transparent"></path></svg>
</template>

// src/react/Gps.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
export const GpsIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { strokeLinejoin:"round",viewBox:"0 0 16 16",width:"1em",height:"1em",dangerouslySetInnerHTML:{__html:'<path d="M1 6L15 1L10 15L7.65955 8.91482C7.55797 8.65073 7.34927 8.44203 7.08518 8.34045L1 6Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="bevel" fill="transparent"></path>'},...p }))
GpsIcon.displayName = 'GpsIcon'
