// packages/vue/src/menu.vue
<template functional>
  <svg aria-hidden="true" height="1em" stroke-linejoin="round" viewBox="0 0 16 16" width="1em"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.75 4H1V5.5H1.75H14.25H15V4H14.25H1.75ZM1.75 10.5H1V12H1.75H14.25H15V10.5H14.25H1.75Z" fill="currentColor"></path></svg>
</template>

// src/react/Menu.ts
import React, { type NamedExoticComponent, type SVGProps } from 'react'
export const MenuIcon: NamedExoticComponent<SVGProps<SVGSVGElement>> = React.memo(p => React.createElement("svg", { height:"16",strokeLinejoin:"round",viewBox:"0 0 16 16",width:"16",dangerouslySetInnerHTML:{__html:'<path fill-rule="evenodd" clip-rule="evenodd" d="M1.75 4H1V5.5H1.75H14.25H15V4H14.25H1.75ZM1.75 10.5H1V12H1.75H14.25H15V10.5H14.25H1.75Z" fill="currentColor"></path>'},...p }))
MenuIcon.displayName = 'MenuIcon'
